layout_spectrum: 0
color:
  saturation: 0.811828
  brandStrength: 0.8854277
  lightness: 0.9480287
  rhythmicContrast: 0.2293907
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.562724
name: Enderly
